import type { Modding } from "@flamework/core";
import * as ecs from "@rbxts/jecs";

import type { Signal } from "./signal";
import { createSignal } from "./signal";

export interface Wrap<T> {
	readonly _flamecs_type: T;
}
export interface Tag extends Wrap<undefined> {}

export interface ChildOf extends Tag {}
export interface Wildcard extends Tag {}
export interface Name extends Wrap<string> {}

export type Id<T = unknown> = ecs.Id<T>;
export type Entity<T = unknown> = ecs.Entity<T>;
export type Pair<P = undefined, O = undefined> = ecs.Pair<P, O>;

export type ExtractPredicate<T> = T extends Pair<infer P, unknown> ? P : T;
export type Unwrap<T> = T extends Wrap<infer Inner> ? Inner : T;

export type ResolveValue<T> = Unwrap<ExtractPredicate<T>>;
export type ResolveValues<T> = { [K in keyof T]: ResolveValue<T[K]> };

export type ComponentKey<T> = Modding.Generic<T, "id">;
export type PairKey<P, O> = Modding.Many<{
	obj: ComponentKey<O extends defined ? O : Wildcard>;
	pred: ComponentKey<P extends defined ? P : Wildcard>;
}>;
export type ResolveKey<T> = T extends Pair<infer P, infer O> ? PairKey<P, O> : ComponentKey<T>;
export type ResolveKeys<T> = Modding.Many<{
	[K in keyof T]: ResolveKey<T[K]>;
}>;

type TrailingUndefined<T extends Array<unknown>> = T extends [...infer Rest, undefined]
	? [...TrailingUndefined<Rest>, undefined?]
	: T;

const components = new Map<string, Entity>();
const IdTocomponents = new Map<Entity, string>();

export const scheduleComponent = new Set<ecs.Entity>();
export const worldSignals = new Map<
	ecs.World,
	{
		added: Map<Entity, Signal<[entity: Entity, data: unknown]>>;
		changed: Map<Entity, Signal<[entity: Entity, data: unknown, prevData: unknown]>>;
		removed: Map<Entity, Signal<[entity: Entity]>>;
	}
>();

/**
 * Returns a signal that fires when a component is added to an entity.
 *
 * @template T - The type of the component.
 * @param key - Flamework autogenerated key for the component.
 * @returns A signal that fires when the component is added to any entity.

 */
export function added<T>(registery: ecs.World, key?: ComponentKey<T>): Signal<[Entity<T>, T]> {
	const id = component(registery, key);
	return worldSignals.get(registery)!.added.get(id)! as Signal<[Entity<T>, T]>;
}

/**
 * Returns a signal that fires when a component is removed from an entity.
 *
 * @template T - The type of the component.
 * @param key - Flamework autogenerated key for the component.
 * @returns A signal that fires when the component is removed from any entity.

 */
export function removed<T>(registery: ecs.World, key?: ComponentKey<T>): Signal<[Entity<T>]> {
	const id = component(registery, key);
	return worldSignals.get(registery)!.removed.get(id)! as Signal<[Entity<T>]>;
}

/**
 * Returns a signal that fires when a component's value changes on an entity.
 *
 * @template T - The type of the component.
 * @param key - Flamework autogenerated key for the component.
 * @returns A signal that fires when the component's value changes on any
 *   entity.

 */
export function changed<T>(
	registery: ecs.World,
	key?: ComponentKey<T>,
): Signal<[entity: Entity<T>, data: T, prevData: T]> {
	const id = component(registery, key);
	return worldSignals.get(registery)!.changed.get(id)! as Signal<[Entity<T>, T, T]>;
}

export function hookListeners(registry: ecs.World, id: Entity): void {
	const addedSignal = createSignal<[Entity, unknown]>();
	const removedSignal = createSignal<[Entity]>();
	const changedSignal = createSignal<[Entity, unknown, unknown]>();
	const signals = worldSignals.get(registry) ?? { added: new Map(), removed: new Map(), changed: new Map() };
	const prevDatas = new Map<Entity, unknown>();
	worldSignals.set(registry, signals);

	signals.added.set(id, addedSignal);
	signals.removed.set(id, removedSignal);
	signals.changed.set(id, changedSignal);

	registry.set(id, ecs.OnAdd, (entity, _, data) => {
		prevDatas.set(entity, data);
		addedSignal.fire(entity, data);
	});
	registry.set(id, ecs.OnRemove, (entity) => {
		prevDatas.delete(entity);
		removedSignal.fire(entity);
	});
	registry.set(id, ecs.OnChange, (entity, _, data) => {
		const prevData = prevDatas.get(entity) ?? data;
		changedSignal.fire(entity, data, prevData);
		prevDatas.set(entity, data);
	});
}

/**
 * Registers an existing entity to the component registry.
 *
 * @template T - The type of the component.
 * @param runtimeId - The runtime entity to be registered.
 * @param key - Flamework autogenerated key.
 * @metadata macro
 */
export function reserve<T>(registry: ecs.World | undefined, runtimeId: Entity<Unwrap<T>>, key?: ComponentKey<T>): void {
	assert(key);
	assert(!components.has(key), `A component with the key "${key}" already exists`);
	components.set(key, runtimeId);
	IdTocomponents.set(runtimeId, key);

	if (registry !== undefined) {
		hookListeners(registry, runtimeId);
		return;
	}

	scheduleComponent.add(runtimeId);
}

function getTypeName(spec: string): string {
	const [match] = string.match(spec, "@([^@]+)$");
	return (match as string) ?? spec;
}

/**
 * Defines a component that can be added to an entity. Components can either tag
 * an entity (e.g., "this entity is an NPC"), store data for an entity (e.g.,
 * "this entity is located at Vector3.new(10, 20, 30)"), or represent
 * relationships between entities <Pair<P, O>> (e.g., "bob Likes alice") that
 * may also store additional data (e.g., "bob Eats 10 apples").
 *
 * @template T - The type of the component.
 * @param key - Flamework autogenerated key.
 * @returns The component entity ID.

 */
export function component<T>(registry?: ecs.World, key?: ComponentKey<T>): Entity<Unwrap<T>> {
	assert(key);
	let id = components.get(key) as Entity<Unwrap<T>> | undefined;

	if (id === undefined) {
		id = ecs.component();

		registry?.set(id, ecs.Name, getTypeName(key));
		components.set(key, id);
		IdTocomponents.set(id, key);

		if (registry !== undefined) {
			hookListeners(registry, id);
			return id;
		}

		scheduleComponent.add(id);
	}

	return id;
}

/**
 * Retrieves the ID of a component or a pair relationship.
 *
 * @template T - The type of the component.
 * @param key - Flamework autogenerated key or pair key.
 * @returns The component or pair ID.
.
 */
export function getId<T>(registry?: ecs.World, key?: ResolveKey<T>): Id<ResolveValue<T>> {
	assert(key);

	if (typeIs(key, "table")) {
		const pairKey = key as PairKey<unknown, unknown>;
		const object = component(registry, pairKey.obj);
		const predicate = component(registry, pairKey.pred);

		return ecs.pair(predicate, object) as never;
	}

	return component(registry, key);
}

export function getKey<T>(runtimeId: Entity) {
	return IdTocomponents.get(runtimeId) as T | undefined;
}

/**
 * Creates a new empty entity.
 *
 * @returns The created entity.

 */
export function spawn(registry: ecs.World): ecs.Tag;

/**
 * Creates a new entity with the specified tag components.
 *
 * @template T - The type of the components.
 * @param keys - Flamework autogenerated keys.
 * @returns The created entity.

 */
export function spawn<T extends Array<Tag>>(registry: ecs.World, keys?: ResolveKeys<T>): ecs.Tag;

/**
 * Creates a new entity with the specified components and their values.
 *
 * @template T - The type of the components.
 * @param values - The values to set for the components.
 * @param keys - Flamework autogenerated keys.
 * @returns The created entity.

 */
export function spawn<T extends Array<unknown>>(
	registry: ecs.World,
	values: TrailingUndefined<ResolveValues<T>>,
	keys?: ResolveKeys<T>,
): ecs.Tag;

export function spawn<T extends Array<unknown>>(
	registry: ecs.World,
	argument1?: unknown,
	argument2?: unknown,
): ecs.Tag {
	const entity = registry.entity();

	if (argument2 !== undefined) {
		// Spawn with components: spawn(values, keys)
		const values = argument1 as TrailingUndefined<ResolveValues<T>>;
		const keys = argument2 as ResolveKeys<T>;

		for (let index = 0; index < keys.size(); index++) {
			const id = getId(registry, keys[index]);
			const value = values[index];
			if (value !== undefined) {
				registry.set(entity, id, value);
			} else {
				registry.add(entity, id as never);
			}
		}
	} else if (argument1 !== undefined) {
		// Spawn with tags only: spawn(keys)
		const keys = argument1 as ResolveKeys<T>;
		for (const key of keys) {
			registry.add(entity, getId(registry, key) as never);
		}
	}

	return entity;
}

/**
 * Deletes the specified entity and all associated components.
 *
 * @param entity - The entity to delete.
 */
export function despawn(registry: ecs.World, entity: Entity): void {
	registry.delete(entity);
}

/**
 * Adds or updates multiple components for the specified entity.
 *
 * @template T - The type of the components.
 * @param entity - The entity to modify.
 * @param keys - Flamework autogenerated keys.

 */
export function insert<T extends Array<Tag>>(registry: ecs.World, entity: Entity, keys?: ResolveKeys<T>): void;

/**
 * Adds or updates multiple components for the specified entity.
 *
 * @template T - The type of the components.
 * @param entity - The entity to modify.
 * @param values - The values to set for the components.
 * @param keys - Flamework autogenerated keys.

 */
export function insert<T extends Array<unknown>>(
	registry: ecs.World,
	entity: Entity,
	values: TrailingUndefined<ResolveValues<T>>,
	keys?: ResolveKeys<T>,
): void;

export function insert<T extends Array<unknown>>(
	registry: ecs.World,
	entity: Entity,
	argument1?: unknown,
	argument2?: unknown,
): void {
	assert(argument1 !== undefined);
	if (argument2 !== undefined) {
		// Insert components: insert(entity, values, keys)
		const values = argument1 as TrailingUndefined<ResolveValues<T>>;
		const keys = argument2 as ResolveKeys<T>;

		for (let index = 0; index < keys.size(); index++) {
			const id = getId(registry, keys[index]);
			const value = values[index];
			if (value !== undefined) {
				registry.set(entity, id, value);
			} else {
				registry.add(entity, id as never);
			}
		}
	} else {
		// Insert tags only: insert(entity, keys)
		const keys = argument1 as ResolveKeys<T>;
		for (const key of keys) {
			registry.add(entity, getId(registry, key) as never);
		}
	}
}

/**
 * Adds a pair relationship with a specific target entity.
 *
 * @template T - The type of the pair.
 * @param entity - The entity to which the pair relationship is added.
 * @param object - The target entity of the relationship (object of the pair).
 * @param key - Flamework autogenerated key.

 */
export function add<T extends Pair<Tag>>(
	registry: ecs.World,
	entity: Entity,
	object: Entity,
	key?: ComponentKey<ExtractPredicate<T>>,
): void;

/**
 * Adds a fully defined pair to an entity. This is used when both the predicate
 * and object of the pair are known at compile-time.
 *
 * @template T - The type of the pair.
 * @param entity - The entity to which the pair component is added.
 * @param key - Flamework autogenerated key.

 */
export function add<T extends Pair<Tag, defined>>(registry: ecs.World, entity: Entity, key?: ResolveKey<T>): void;

/**
 * Adds a component to an entity.
 *
 * @template T - The type of the component.
 * @param entity - The entity to which the component is added.
 * @param key - Flamework autogenerated key.

 */
export function add<T extends Tag>(registry: ecs.World, entity: Entity, key?: ComponentKey<T>): void;

export function add(registry: ecs.World, entity: Entity, argument1?: unknown, argument2?: unknown): void {
	if (argument2 !== undefined) {
		// Pair<P, _> case: add(entity, object, key)
		const object = argument1 as Entity;
		const key = argument2 as ComponentKey<unknown>;
		registry.add(entity, ecs.pair(component(registry, key), object) as never);
	} else {
		// Known component case: add(entity, key)
		const key = argument1 as ResolveKey<unknown>;
		registry.add(entity, getId(registry, key) as never);
	}
}

/**
 * Removes a pair relationship with a specific target entity.
 *
 * @template T - The type of the pair.
 * @param entity - The entity from which the pair relationship is removed.
 * @param object - The target entity of the relationship (object of the pair).
 * @param key - Flamework autogenerated key.

 */
export function remove<T extends Pair<defined>>(
	registry: ecs.World,
	entity: Entity,
	object: Entity,
	key?: ComponentKey<ExtractPredicate<T>>,
): void;

/**
 * Removes a fully defined pair from an entity. This is used when both the
 * predicate and object of the pair are known at compile-time.
 *
 * @template T - The type of the pair.
 * @param entity - The entity from which the pair component is removed.
 * @param key - Flamework autogenerated key.

 */
export function remove<T extends Pair<defined, defined>>(
	registry: ecs.World,
	entity: Entity,
	key?: ResolveKey<T>,
): void;

/**
 * Removes a component from an entity.
 *
 * @template T - The type of the component.
 * @param entity - The entity from which the component is removed.
 * @param key - Flamework autogenerated key.

 */
export function remove<T>(registry: ecs.World, entity: Entity, key?: ComponentKey<T>): void;

export function remove(registry: ecs.World, entity: Entity, argument1?: unknown, argument2?: unknown): void {
	if (argument2 !== undefined) {
		// Pair<P, _> case: remove(entity, object, key)
		const object = argument1 as Entity;
		const key = argument2 as ComponentKey<unknown>;
		registry.remove(entity, ecs.pair(component(registry, key), object));
	} else {
		// Known component case: remove(entity, key)
		const key = argument1 as ResolveKey<unknown>;
		registry.remove(entity, getId(registry, key));
	}
}

/**
 * Sets a value for a pair with a specific runtime target entity.
 *
 * @template T - The type of the pair.
 * @param entity - The entity to which the pair relationship is added.
 * @param object - The target entity of the relationship (object of the pair).
 * @param value - The value associated with the pair relationship.
 * @param key - Flamework autogenerated key.

 */
export function set<T extends Pair<defined>>(
	registry: ecs.World,
	entity: Entity,
	object: Entity,
	value: ResolveValue<T>,
	key?: ComponentKey<ExtractPredicate<T>>,
): void;

/**
 * Sets a value for a fully defined pair on an entity. This is used when both
 * the predicate and object of the pair are known at compile-time.
 *
 * @template T - The type of the pair.
 * @param entity - The entity to which the pair component is added.
 * @param value - The value associated with the pair component.
 * @param key - Flamework autogenerated key.

 */
export function set<T extends Pair<defined, defined>>(
	registry: ecs.World,
	entity: Entity,
	value: ResolveValue<T>,
	key?: ResolveKey<T>,
): void;

/**
 * Sets a value for a component on an entity.
 *
 * @template T - The type of the component.
 * @param entity - The entity to which the component is added or updated.
 * @param value - The value associated with the component.
 * @param key - Flamework autogenerated key.
 */
export function set<T>(registry: ecs.World, entity: Entity, value: Unwrap<T>, key?: ComponentKey<T>): void;

export function set(
	registry: ecs.World,
	entity: Entity,
	argument1: unknown,
	argument2?: unknown,
	argument3?: unknown,
): void {
	if (argument3 !== undefined) {
		// Pair<P, _> case: set(entity, object, value, key)
		const object = argument1 as Entity;
		const value = argument2;
		const key = argument3 as ComponentKey<unknown>;
		registry.set(entity, ecs.pair(component(registry, key), object), value);
	} else {
		// Known component case: set(entity, value, key)
		const value = argument1;
		const key = argument2 as ResolveKey<unknown>;
		registry.set(entity, getId(registry, key), value);
	}
}

/**
 * Retrieves the value of a pair relationship for a specific entity and target.
 *
 * @template T - The type of the pair.
 * @param entity - The entity from which to retrieve the pair relationship.
 * @param object - The target entity of the relationship (object of the pair).
 * @param key - Flamework autogenerated key.
 * @returns The value associated with the pair relationship.
 */
export function get<T extends Pair<defined>>(
	registry: ecs.World,
	entity: Entity,
	object: Entity,
	key?: ComponentKey<ExtractPredicate<T>>,
): ResolveValue<T> | undefined;

/**
 * Retrieves the value of a component or pair for a specific entity.
 *
 * @template T - The type of the component or pair.
 * @param entity - The entity from which to retrieve the component or pair.
 * @param key - Flamework autogenerated key.
 * @returns The value associated with the component or pair.
 */
export function get<T>(registry: ecs.World, entity: Entity, key?: ResolveKey<T>): ResolveValue<T> | undefined;

export function get(registry: ecs.World, entity: Entity, argument1?: unknown, argument2?: unknown): unknown {
	if (argument2 !== undefined) {
		// Pair<P, _> case: get(entity, object, key)
		const object = argument1 as Entity;
		const key = argument2 as ComponentKey<unknown>;
		return registry.get(entity, ecs.pair(component(registry, key), object));
	}

	// Known component case: get(entity, key)
	const key = argument1 as ResolveKey<unknown>;
	return registry.get(entity, getId(registry, key));
}

/**
 * Checks if a pair relationship exists for a specific entity and target.
 *
 * @template T - The type of the pair.
 * @param entity - The entity to check for the pair relationship.
 * @param object - The target entity of the relationship (object of the pair).
 * @param key - Flamework autogenerated key.
 * @returns True if the pair relationship exists, false otherwise.

 */
export function has<T extends Pair<defined>>(
	registry: ecs.World,
	entity: Entity,
	object: Entity,
	key?: ComponentKey<ExtractPredicate<T>>,
): boolean;

/**
 * Checks if a component or pair exists for a specific entity.
 *
 * @template T - The type of the component or pair.
 * @param entity - The entity to check for the component or pair.
 * @param key - Flamework autogenerated key.
 * @returns True if the component or pair exists, false otherwise.

 */
export function has<T>(registry: ecs.World, entity: Entity, key?: ResolveKey<T>): boolean;

export function has(registry: ecs.World, entity: Entity, argument1?: unknown, argument2?: unknown): boolean {
	if (argument2 !== undefined) {
		// Pair<P, _> case: has(entity, object, key)
		const object = argument1 as Entity;
		const key = argument2 as ComponentKey<unknown>;
		return registry.has(entity, ecs.pair(component(registry, key), object));
	}

	// Known component case: has(entity, key)
	const key = argument1 as ResolveKey<unknown>;
	return registry.has(entity, getId(registry, key));
}

/**
 * Retrieves the target entity of a relationship involving the specified entity
 * and component.
 *
 * @template T - The type of the component.
 * @param entity - The entity to get the target for.
 * @param key - Flamework autogenerated key.
 * @returns The target entity if a relationship exists, or undefined otherwise.

 */
export function target<T>(registry: ecs.World, entity: Entity, key?: ComponentKey<T>): Entity | undefined {
	const id = component(registry, key);
	return registry.target(entity, id);
}

/**
 * Retrieves the parent entity (target of the ChildOf relationship) for the
 * given entity.
 *
 * @param entity - The entity for which to get the parent.
 * @returns The parent entity, or undefined if no parent exists.
 */
export function parent(registry: ecs.World, entity: Entity): Entity | undefined {
	return target<ChildOf>(registry, entity);
}

/**
 * Creates a pair relationship between a component and an entity.
 *
 * @template P - The type of the predicate component.
 * @template O - The type of the object component.
 * @param object - The object entity.
 * @param predicate - The predicate component key.
 * @returns The pair ID.

 */
export function pair<P>(registry: ecs.World, object: Entity, predicate?: ComponentKey<P>): Pair<Unwrap<P>, unknown> {
	const predicateId = component(registry, predicate);
	return ecs.pair(predicateId, object);
}

export function initWorld(registry: ecs.World) {
	reserve<Wildcard>(registry, ecs.Wildcard as never);
	reserve<ChildOf>(registry, ecs.ChildOf as never);
	reserve<Name>(registry, ecs.Name);
}
